### ISSUE TITLE
New Owner Wanted

### ISSUE THREAD

**Issue by edent** [rahuldottech/Dabr#147]
Dabr.eu will go offline on Sep 30, 2019.  I don't have the time or resources to keep Dabr.eu running.  This is for a few reasons:

* New domain rules mean that UK citizens won't be able to own .eu domain names if we exit the EU.
* I don't have the time to keep up with the Twitter API changes.
* The number of users of Dabr is dropping - around 500 per day
* Hosting costs are cheap - but I'd rather not have it clogging up my server.

I am happy to transfer the domain for free to anyone who wants to run the service. 

![dabr](https://user-images.githubusercontent.com/837136/56848374-1b360980-68e0-11e9-9d6f-c106846b77cb.png)

![bandwidth](https://user-images.githubusercontent.com/837136/56848373-1b360980-68e0-11e9-981a-b6d1e108e5a9.png)

**Comment by crablab** [comment]
I'm happy to maintain this :+1:  

I have the server capacity and as I do a lot of PHP stuff anyway!

**Comment by edent** [comment]
@crablab You'll need to be based in the EU in order to take the .eu domain - see https://news.gandi.net/en/2019/03/the-impact-of-brexit-on-eu-domains/

**Comment by crablab** [comment]
@edent Sure - but how important is the domain vs maintaining the project? :)

**Comment by rahuldottech** [comment]
I'm happy to take over! I'll check with my registrar and message you soon.

**Comment by edent** [comment]
@rahuldottech I'll transfer the domain on Saturday to your Irish registrar, then move this repo over to you.
@crablab I'm sure Rahul will appreciate any Pull Requests.
